In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [2]:
df=pd.read_csv("price.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

3

In [4]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [5]:
reg=linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [6]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [7]:
reg.intercept_

383725.0

In [8]:
d=pd.DataFrame({"area":[3000,2500],"bedrooms":[3,4],"age":[40,5]})

In [9]:
d

area  bedrooms  age
0  3000         3   40
1  2500         4    5

In [10]:
reg.predict(d)

array([444400., 588625.])

# Exercise


In [11]:
df2=pd.read_csv("salary.csv")
df2

exp  test  interview  salary
0     NaN   8.0          9   50000
1     NaN   8.0          6   45000
2    five   6.0          7   60000
3     two  10.0         10   65000
4   seven   9.0          6   70000
5   three   7.0         10   62000
6     ten   NaN          7   72000
7  eleven   7.0          8   80000

In [12]:
from word2number import w2n

In [13]:
df2.exp=df2.exp.fillna("zero")
df2

exp  test  interview  salary
0    zero   8.0          9   50000
1    zero   8.0          6   45000
2    five   6.0          7   60000
3     two  10.0         10   65000
4   seven   9.0          6   70000
5   three   7.0         10   62000
6     ten   NaN          7   72000
7  eleven   7.0          8   80000

In [14]:
df2.exp=df2.exp.apply(w2n.word_to_num)

In [15]:
median_test=df2.test.median()
median_test

8.0

In [16]:
df2.test=df2.test.fillna(median_test)

In [17]:
df2

exp  test  interview  salary
0    0   8.0          9   50000
1    0   8.0          6   45000
2    5   6.0          7   60000
3    2  10.0         10   65000
4    7   9.0          6   70000
5    3   7.0         10   62000
6   10   8.0          7   72000
7   11   7.0          8   80000

In [18]:
model=linear_model.LinearRegression()
model.fit(df2[["exp","test","interview"]],df2.salary)

LinearRegression()

In [19]:
d2=pd.DataFrame({"exp":[2,12],"test":[9,10],"interview":[6,10]})
d2

exp  test  interview
0    2     9          6
1   12    10         10

In [20]:
model.predict(d2)

array([53205.96797671, 92002.18340611])